name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.2'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: gofmt
        run: make gofmt

      - name: govet
        run: make govet

      - name: go mod verify
        run: go mod verify

      - name: Test
        run: make test

      - name: Build
        run: make build

      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}