name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: gofmt
        run: make gofmt

      - name: govet
        run: make govet

      - name: Linting
        run: |
            go install honnef.co/go/tools/cmd/staticcheck@latest
            staticcheck ./...

      - name: govulncheck
        run: |
            go install golang.org/x/vuln/cmd/govulncheck@latest
            govulncheck ./...

      - name: go mod verify
        run: go mod verify

      - name: Test
        run: make test

      - name: Build
        run: make build

      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
